#!/usr/bin/env node
// THFC Dashboard — build script (v2, esbuild-powered)
// Run: node build.js
//
// Reads all source files from data/, lib/, components/, concatenates and
// JSX-compiles + minifies them via esbuild, then INLINES that bundle
// directly into docs/index.html using src/index-template.html as the shell.
// Also copies manifest.json and sw.js into docs/ for PWA support.
//
// docs/index.html + docs/bundle.js + docs/manifest.json + docs/sw.js are what you deploy to
// GitHub Pages (or load in Electron). docs/bundle.js is retained as the
// compiled artifact alongside the self-contained HTML shell.
//
// CHANGE FROM v1: JSX used to be shipped raw and parsed live in the browser
// by Babel Standalone (~1.5MB library, parsed on every page load). Now it's
// compiled ahead of time here, once, at build time — smaller, faster,
// no Babel download at all. Requires `npm install` once (esbuild only).

const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');
const { execSync } = require('child_process');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'docs');

// ── Step 0: secret scan ─────────────────────────────────────────────────────
// Refuses to build if a live-looking API key is found anywhere it shouldn't
// be (see scripts/check-secrets.js). automation/.env is allowed since it's
// gitignored and never read by this script.
try {
  execSync('node scripts/check-secrets.js', { cwd: ROOT, stdio: 'inherit' });
} catch {
  console.error('\nBuild aborted — fix the secret scan failure above first.\n');
  process.exit(1);
}

if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR);

// Read a file and strip import/export statements for bundling
function readModule(filePath) {
  let src = fs.readFileSync(filePath, 'utf8');
  src = src.replace(/^import\s+.*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '');
  src = src.replace(/^import\s+['"][^'"]+['"]\s*;?\s*$/gm, '');
  src = src.replace(/^export\s+(default\s+)?/gm, '');
  return src.trim();
}

// Order matters — dependencies before consumers
const FILES = [
  'data/theme.js',
  'data/standings.js',
  'data/squad.js',
  'data/transfers.js',
  'data/finances.js',
  'data/news.js',
  'data/records.js',
  'data/worldcup.js',
  'data/fixtures.js',
  'lib/shared.js',
  'lib/charts.js',
  'components/OverviewPanel.js',
  'components/SquadPanel.js',
  'components/InjuriesPanel.js',
  'components/FixturesPanel.js',
  'components/TransfersPanel.js',
  'components/FinancesPanel.js',
  'components/RecordsPanel.js',
  'components/NewsPanel.js',
  'components/WorldCupPanel.js',
  'components/RightFeed.js',
  'components/PlayerDetail.js',
  'components/App.js',
];

const banner = `// THFC Dashboard — Auto-generated bundle. DO NOT EDIT THIS FILE.
// Edit source files in data/, lib/, components/ then run: node build.js
// Built: ${new Date().toISOString()}
const { useState, useEffect } = React;
const BUILD_DATE = ${JSON.stringify(new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase())};
`;

// ── Guard rail: catch new files that were added under src/ but never added
// to FILES above. This is a real failure mode, not hypothetical — FILES is
// a hand-maintained list, readModule() strips import/export lines whether
// or not the imported file is actually in the bundle, and esbuild has no
// way to know a component is missing until it ReferenceErrors in the
// browser at runtime. Fail the build loudly instead.
for (const dir of ['data', 'lib', 'components']) {
  const dirPath = path.join(ROOT, 'src', dir);
  const onDisk = fs.readdirSync(dirPath).filter(f => f.endsWith('.js'));
  const missing = onDisk.filter(f => !FILES.includes(`${dir}/${f}`));
  if (missing.length) {
    console.error(`\n⚠️  Found file(s) in src/${dir}/ that aren't in build.js's FILES list:`);
    missing.forEach(f => console.error(`   - ${dir}/${f}`));
    console.error('   Add them to FILES (in dependency order) or the build will silently omit them.\n');
    process.exit(1);
  }
}

const parts = [banner];
for (const f of FILES) {
  const full = path.join(ROOT, 'src', f);
  if (!fs.existsSync(full)) {
    console.error('MISSING:', full); process.exit(1);
  }
  parts.push(`\n// ── ${f} ──`);
  parts.push(readModule(full));
}

parts.push(`\nReactDOM.createRoot(document.getElementById("root")).render(React.createElement(App));`);

const rawBundle = parts.join('\n');

// ── Step 1: compile JSX -> plain JS ─────────────────────────────────────────
// esbuild's default classic JSX transform emits React.createElement(...) /
// React.Fragment calls, which matches the global `React` UMD build loaded
// in index-template.html — no extra config needed.
let compiled;
try {
  compiled = esbuild.transformSync(rawBundle, {
    loader: 'jsx',
    target: 'es2018',
    minify: false, // minify in a separate pass below, after we can still read errors clearly if this step fails
  }).code;
} catch (err) {
  console.error('\n JSX compile failed — check the syntax in the file(s) listed below:\n');
  console.error(err.message);
  process.exit(1);
}

// ── Step 2: minify ───────────────────────────────────────────────────────────
let minified;
try {
  minified = esbuild.transformSync(compiled, {
    minify: true,
    target: 'es2018',
  }).code;
} catch (err) {
  console.error('\n Minification failed:\n', err.message);
  process.exit(1);
}

// ── Step 3: inline into HTML shell ──────────────────────────────────────────
const TEMPLATE_PATH = path.join(ROOT, 'src', 'index-template.html');
if (!fs.existsSync(TEMPLATE_PATH)) {
  console.error('MISSING template:', TEMPLATE_PATH);
  process.exit(1);
}
const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
if (!template.includes('/*__BUNDLE__*/')) {
  console.error('src/index-template.html is missing the /*__BUNDLE__*/ placeholder.');
  process.exit(1);
}
const finalHtml = template.replace('/*__BUNDLE__*/', minified);

fs.writeFileSync(path.join(OUT_DIR, 'index.html'), finalHtml);
fs.writeFileSync(path.join(OUT_DIR, 'bundle.js'), minified);

// ── Step 4: copy PWA assets ──────────────────────────────────────────────────
fs.copyFileSync(path.join(ROOT, 'src', 'manifest.json'), path.join(OUT_DIR, 'manifest.json'));

// sw.js gets its CACHE_NAME version stamped in at build time (see __BUILD_VERSION__
// placeholder in src/sw.js) rather than copied verbatim — this is what makes every
// build automatically invalidate old clients' service-worker cache. Without this,
// returning visitors could get served a stale index.html indefinitely, since browsers
// only re-install a service worker when its file content actually changes.
const swTemplate = fs.readFileSync(path.join(ROOT, 'src', 'sw.js'), 'utf8');
if (!swTemplate.includes('__BUILD_VERSION__')) {
  console.error('src/sw.js is missing the __BUILD_VERSION__ placeholder — cache-busting would silently stop working.');
  process.exit(1);
}
const buildVersion = Date.now().toString(36);
const swFinal = swTemplate.replace(/__BUILD_VERSION__/g, buildVersion);
fs.writeFileSync(path.join(OUT_DIR, 'sw.js'), swFinal);

// ── Step 5: smoke check ──────────────────────────────────────────────────────
// Basic sanity: root div present, bundle isn't suspiciously tiny (a sign the
// replace() silently failed), no leftover unresolved import/export keywords.
const problems = [];
if (!finalHtml.includes('id="root"')) problems.push('Missing <div id="root">');
if (minified.length < 5000) problems.push(`Bundle suspiciously small (${minified.length} bytes) — did a file fail to concatenate?`);
if (/^\s*(import|export)\s/m.test(minified)) problems.push('Unresolved import/export keyword survived into the bundle');
if (swFinal.includes('__BUILD_VERSION__')) problems.push('sw.js still contains an unresolved __BUILD_VERSION__ placeholder — cache-busting silently broken');
if (problems.length) {
  console.error('\n⚠️  Build produced output but failed smoke checks:');
  problems.forEach(p => console.error('   - ' + p));
  process.exit(1);
}

const rawKB = Math.round(Buffer.byteLength(rawBundle) / 1024);
const minKB = Math.round(Buffer.byteLength(minified) / 1024);
console.log(`\n✓ Build passed smoke checks.`);
console.log(`  docs/index.html   ${Math.round(finalHtml.length / 1024)}KB total (bundle: ${rawKB}KB source -> ${minKB}KB minified)`);
console.log(`  docs/manifest.json copied, docs/sw.js versioned (cache: thfc-dashboard-${buildVersion})`);
console.log(`  Commit the tracked docs/ output to main for GitHub Pages deployment.\n`);
